### ISSUE TITLE
matrix-org kann nicht auf Server zugreifen

### ISSUE THREAD

**Issue by Chiller2019** [oelison/ioBroker.matrix-org#20]
**Describe the bug**  
Fehler in Log sichtbar allerdings nicht nachvollziehbar.

**To Reproduce**  
1. Erstelle Nutzer
2. Logge dich ein mit den Nutzer, geh in den Raum
3. Credentials in ioBroker eingeben
4. Log sehen

1**Expected behavior**  
Adapter funktioniert nicht obwohl mit Sicherheit die Creds korrekt sind.
Ping auf dem Matrix-Server funktioniert einwandfrei. Keine Fehler zu erkennen.

**Screenshots & Logfiles**  
```
1. ConnectionError: request failed: connect ECONNREFUSED 192.168.XXX:8008 (auch 8448 probiert)
2. Server or room not found. Check port (443/8448), room name and server.
```

**Versions:**  
 - Adapter version: 0.1.3
 - JS-Controller version: 4.0.32
 - Node version: 16.18.1
 - Operating system: Rasbian

**Comment by Chiller2019** [comment]
Neuer Fehler auf Port 443

`
ConnectionError: request failed: unable to verify the first certificate
`

Leider fehlt hier die Option das rootCA einzufügen oder das Zertifikat schlichtweg zu ignorieren.

**Comment by oelison** [comment]
I have set this as enhancement. The first part is not the bug. I think a flag for ignoring the SSL root chain will be a feature request.

**Comment by oelison** [comment]
matrix-js-sdk is used in the adapter. First search show this old issue:
https://github.com/matrix-org/matrix-js-sdk/issues/250

**Comment by fir3drag0n** [comment]
is there a solution?

**Comment by oelison** [comment]
> is there a solution?

No. Don't use a self signed certificate. You need an official chain of trust. No other solution is wanted.

**Comment by oelison** [comment]
Quite old bug. Please reopen if anyone have more information.
