### ISSUE TITLE
No error log when room is wrong

### ISSUE THREAD

**Issue by oelison** [oelison/ioBroker.matrix-org#3]
When the room does not exist or wrongly formatted, no error is reported and adapter looks like running.

**To Reproduce**  
1. Configure server and a wrong room 
2. Name and password could be ok
3. Restart adapter 
4. RoomId is null

**Expected behavior**  
Report error in the log, that the room is not available.

**Versions:**  
 - Adapter version: v0.0.5

**Comment by Rudi1982** [comment]
Morgen...

Hab gestern noch ein wenig getestet.

Wenn ich bei Server "https://matrix.org" habe, steht folgendes im Log:

`
matrix-org.0 | 2022-07-10 10:21:08.923 | error | Server not reached! https://matrix.org:8448 with room: #xxxxxx

matrix-org.0 | 2022-07-10 10:21:08.922 | error | Error: connect ETIMEDOUT 104.20.201.37:8448
`

Wenn ich bei Server "matrix.org" habe, steht folgendes im Log:

`
matrix-org.0 | 2022-07-10 10:24:27.637 | error | Server not reached! matrix.org:8448 with room: #xxxxxxx

matrix-org.0 | 2022-07-10 10:24:27.636 | error | Error: connect EHOSTUNREACH 37.120.175.103:8448
`
In beiden Fällen hab ich unter objechts folgendes stehen:

matrix-org/0/info/connection                       false
matrix-org/0/martixServerData/roomID      (null)

Somit scheint das Problem bei dem eingegebenen Server zu sein und kommt nicht mal zum eingegebenen Raum oder liege ich falsch?

Lg

**Comment by oelison** [comment]
Hi. Das https:// setzt der Adapter davor, brauch also nicht angegeben werden. (Ohne https macht das keinen Sinn für mich). Ich habe jetzt mal einen Öffentlichen Testraum in der Matrix angelegt. https://matrix.org:8448/_matrix/client/r0/directory/room/%23test-ioBroker-adapter:matrix.org funktioniert nicht, da matrix.org ein proxy verwendet. Da ist der port dann 443.
Dann kommt bei mir: {"room_id":"!gapLtrCXsCQJDMauOT:matrix.org","servers":["matrix.org"]} zurück.

**Comment by oelison** [comment]
In die ersten drei Felder ist alse folgendes ein zu geben:
Server: matrix.org Port: 443
room: #test-ioBroker-adapter:matrix.org
Der Bot sollte dem Raum schon beigetreten sein.

**Comment by Rudi1982** [comment]
Funktioniert... Danke

**Comment by oelison** [comment]
Danke fürs Testen. Ich werde einen Hinweis in die ReadMe.md rein setzten. Und die Debugausgaben erhöhen, wenn was schief geht.

**Comment by Rudi1982** [comment]
Ich hab zu Danken... Schließlich wurde erst durch dich der Adapter umgesetzt...

Lg

**Comment by Rudi1982** [comment]
Ich weiß nicht, ob es hier passt, aber ich wolte keine neue issue öffnen, da hier ja eigentlich die grundsätzliche Funktion getestet wird, wie zB Senden einer Nachricht (siehe meinen vorherigen Post).

Aber ist es möglich, dass der Adapter auch auf eingehende Nachrichten reagiert? Wäre interessant für Statusabfragen, etc.

LG

**Comment by oelison** [comment]
v0.0.6 solve this issue.
