### ISSUE TITLE
Empfangen von Nachrichten

### ISSUE THREAD

**Issue by Rudi1982** [oelison/ioBroker.matrix-org#5]
**Is your feature request related to a problem? Please describe.**
Teilweise... Durch das Empfangen von Nachrichten könnte man mit Signal zB Statusabfragen (Stromverbrauch, Fenster geschlossen, etc) schicken und gewisse Zustände abfragen.

**Describe the solution you'd like**
Ich stelle mir das Ganze folgendermaßen vor:
Der Adapter bekommt nen neuen Datenpunkt, der zur Speicherung der letzten empfangenen Nachricht im Raum dient. Nachrichten könnte man mit einem Polling von zB 10 - xx Sekunden (einstellbar um ein gutes Timing zu erzielen und trotzdem nicht unnötig Speicher belegt wird) abfragen. Somit könnte der User dann Schlüsselwörter in einem JS- oder Blockly-Script erstellen und den DP via Script überwachen. Dadurch könnte das Script auf die Schlüsselwörter reagieren und via sendTo-Command ne Antwort-Nachricht an den Adapter zuückgeben, um sie dann verschicken zu können.

LG, Rudi1982

**Comment by oelison** [comment]
[https://github.com/oelison/ioBroker.matrix-org/commit/49242fda4c5160ef707f270acb30e86dfe1995bf](Check this for testing)

**Comment by FeLLa-23** [comment]
I can confirm the feature is working in current master. Thanks for your work @oelison!

**Comment by oelison** [comment]
Release-0.0.7
