### ISSUE TITLE
M_INVALID_PARAM

### ISSUE THREAD

**Issue by Friedjof** [oelison/ioBroker.matrix-org#54]
Hi,
ich habe jetzt die Version 1.0.0 und die Version 0.1.6 ausprobiert und ich bekomme immer diesen Fehler:
```
Server or room not found. Check port (443/8448), room name and server.
{"errcode":"M_INVALID_PARAM","data":{"errcode":"M_INVALID_PARAM","error":"Room alias invalid"},"httpStatus":400,"name":"M_INVALID_PARAM"}
```
Ich habe node v18.19.0 und sonst ist mein ioBroker auch auf dem neusten Stand.
Alle dort konfigurierten Einstellungen habe ich bereits mehrfach verifiziert und auch einfach 1:1 von Element aus kopiert.
![grafik](https://github.com/oelison/ioBroker.matrix-org/assets/60787233/364dcfe3-7dcf-4884-94df-e26f64f90e75)
Ich habe die Ports 443 und 8448 ausprobiert und auch direkt die IP von matrix.org dort eingegeben.

Gibt es da eine Lösung für? Bzw ist das Problem bekannt?

Schonmal vielen Dank im voraus :relaxed:

**Comment by oelison** [comment]
Hi @Friedjof ,
Readme Auszug:
If you like to test it: Server: matrix.org Port: 443 room: #test-ioBroker-adapter:matrix.org Join this room and try it out with your own credentials
Bitte versuch das erstmal mit diesem Raum. Wichtig ist, das der User, der im ioBroker verwendet werden soll in dem Raum schon drin ist. (Eingeladen geht auch, aber dann muß der Autojoin Haken gesetzt sein und klappt leider nicht immer)
Wenn das da auch nicht geht, wird es spannend.
Wenn es da geht, dann ist der Raum wahrscheinlich verschlüsselt. Leider kann ich noch nicht in Verschlüsselte Räume rein. Mit Node 18 sollte das gehen, habe aber noch keine Zeit gefunden mich darum zu kümmern. Siehe Ticket #7 .

**Comment by oelison** [comment]
Überigens: Matrix.org ist immer 443. Nur selbst aufgesetzte Server haben oft 8448 oder einen ganz anderen Port.

**Comment by Friedjof** [comment]
Ah, ok. Jetzt hat es bei mir funktioniert.
Ich wäre auf jeden Fall auch an der Unterstützung verschlüsselter Raume interessiert.
Aber ich verstehe natürlich auch, dass das vermutlich nicht so einfach ist.
Vielen Dank für deine Unterstützung :D
