### ISSUE TITLE
Zugriff auf selbstgehosteten Server nicht möglich 

### ISSUE THREAD

**Issue by daKrueml** [oelison/ioBroker.matrix-org#56]
**Describe the bug**  
Bei der Verbindung auf unseren selbstgehosteten Matrix Server wird ein 404 Error geworfen:

matrix-org.0 | 2024-08-15 13:33:46.420 | error | {"httpStatus":404}
matrix-org.0 | 2024-08-15 13:33:46.420 | error | Server or room not found. Check port (443/8448), room name and server.

Eine identisch-abgewandelte Konfiguration funktioniert auf matrix.org. 

Der Raum ist für den Test öffentlich und auch im Verzeichnis gelistet, ohne Zutrittsbeschränkungen. Der Botuser ist dem Raum auch schon beigetreten.

Interessant ist, dass das Server Log nur Spuren von von der 404 Antwort zur Raumanfrage enthält, der Client sich aber scheinbar niemals anmeldet. 

Aug 13 20:16:26 v2202204173924187400 matrix-traefik[601517]: **** - - [13/Aug/2024:18:16:26 +0000] "GET /_matrix/client/r0/directory/room/%23immanuel-iobroker%3A***.de HTTP/1.1" 404 72 "-" "-" 1835 "matrix-static-files-base-domain@docker" "http://172.23.0.2:8080" 0ms

**Versions:**  
 - Adapter version: 1.0.0
 - JS-Controller version: 6.0.9
 - Node version: v20.16.0
 - Operating system: debian

**Comment by oelison** [comment]
Hi,
Schon mal den Fehler #20 angesehen? Selbstsignierte Zertifikate gehen nicht. Ich habe auch einen selbsgehosteten matrix server laufen. Der läuft auf meiner Domain und ist mit lets encrypt Zerifiziert. Der Testraum ist auch dort. Wichtig ist auch das die Räume nicht verschlüsselt sind. Das aktuelle SDK kann verschlüsselte Räume nicht. Ich will mal auf Matrix Bot SDK umstellen, aber bisher noch keine Zeit gehabt. (Auch da werden selbstsignierte Zertifikate nicht gehen. Das scheint von Matrix selbst nicht gewollt zu sein.

**Comment by daKrueml** [comment]
Moin! Klar hab ich den gesehen. Der Server ist korrekt konfiguriert und ist
mit öffentlicher IP und sauberen Zertifikaten im Netz.

Christian Oelschlegel ***@***.***> schrieb am Fr., 16. Aug.
2024, 12:09:

**Comment by oelison** [comment]
Schon mal versucht als dieser User den Raum zu betreten mit Element oder so. Manchmal reicht die Einladung nicht. So dass der User gar nicht in den Raum kommt.

**Comment by daKrueml** [comment]
Steht in der Beschreibung. Der User ist schon im Raum.

Christian Oelschlegel ***@***.***> schrieb am Fr., 16. Aug.
2024, 15:03:

**Comment by oelison** [comment]
Schau nochmal in #20 und schreib mir direkt auf matrix. (da ist meine Addresse)
Dann kann ich mal versuchen bei mir eine instanz anzulegen und zu debuggen.

**Comment by daKrueml** [comment]
Kurz zusammengefasst: Es war ein Konfigurationsproblem des Servers was wir noch genauer identifizieren müssen. Als Workaround für alle die das Problem auch bekommen: Als Host im Adapter matrix.<domain> eintragen hat geholfen.
