### ISSUE TITLE
Senden von Dateien, Fotos, etc

### ISSUE THREAD

**Issue by Rudi1982** [oelison/ioBroker.matrix-org#6]
**Is your feature request related to a problem? Please describe.**
Dieses Feature wäre beim Einsatz von Kameras sinnvoll. Damit könnte man zB beim Auslösen eines Alarmes gleich einen Screenshot oder Video der Kamera an das Handy schicken, falls zb Niemand zuhause ist...

LG, Rudi1982

**Comment by oelison** [comment]
For testing a branch is ready: https://github.com/oelison/ioBroker.matrix-org/tree/6-sending-files-images

**Comment by oelison** [comment]
Retry this branch for local files. Only tested with windows. But will work with linux I guess.
@Rudi1982

**Comment by oelison** [comment]
I have updated the branch again. Base64 sending is a little bit adjusted to json format.
I think about to expect the mimeType from the callers function. Any ideas against this? Guessing the mime type is quite difficult.
