### ISSUE TITLE
Support html subset from Matrix 

### ISSUE THREAD

**Issue by binarious** [oelison/ioBroker.matrix-org#9]
**Is your feature request related to a problem? Please describe.**
Using Markdown (like `**bold** text` or `[My Link](https://myurl.com)`) results in plain text instead of a Markdown interpreted message.

**Describe the solution you'd like**
It would be great to have the message Markdown interpreted.

**Comment by oelison** [comment]
In the matrix protocol only html is defined. And also only a subset. 
So what I could assume is to open an interface for html messages. The results will be very different on each client. So it is on the users side to try out what is working. 
Element for example is converting the markdown input into html. You could see the result when you look at the code of a send message. But it looks very complex. Please give a comment on the approach.

**Comment by oelison** [comment]
See:
https://github.com/matrix-org/matrix-spec-proposals/issues/1225
https://github.com/matrix-org/matrix-spec-proposals/pull/1562

**Comment by oelison** [comment]
```
{
  "type": "m.room.message",
  "sender": "@abcde:abcde.de",
  "content": {
    "org.matrix.msc1767.message": [
      {
        "body": "test **with mark down**",
        "mimetype": "text/plain"
      },
      {
        "body": "test <strong>with mark down</strong>",
        "mimetype": "text/html"
      }
    ],
    "body": "test **with mark down**",
    "msgtype": "m.text",
    "format": "org.matrix.custom.html",
    "formatted_body": "test <strong>with mark down</strong>"
  },
  "origin_server_ts": 13242342316,
  "unsigned": {
    "age": 1
  },
  "event_id": "$AAAAAAAAAAAAAAA_A_AAAAA-AAAAAAAAAAAAAAA",
  "room_id": "!AAAAAAAAAAAAA:abcde.de"
}
```

**Comment by binarious** [comment]
I see. Didn't know that. HTML support would be nice then, if that's feasable. Shall I rename the issue?

**Comment by oelison** [comment]
I have renamed it.

**Comment by oelison** [comment]
Looks fine. See one result copied into #test-ioBroker-adapter:matrix.org

**Comment by binarious** [comment]
I just see `12ab` as an unformatted message in Element.
